import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import type { RouterOutputs, } from "~/utils/api";
import { SignInButton, SignOutButton, SignUp, useUser } from "@clerk/nextjs";
import { SignIn } from "@clerk/nextjs";
import dayjs from "dayjs"
import relativeTime from "dayjs/plugin/relativeTime"
import Image from "next/image";
dayjs.extend(relativeTime);
export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const user = useUser();

  const { data, isLoading } = api.post.getAll.useQuery();
  type PostWithUser = RouterOutputs["post"]["getAll"][number];
  const PostView = (props: PostWithUser) => {
    const { post, author } = props;
    return (
      <div key={post.id} className="border-b border-slate-400 p-8 flex gap-3">
        <Image
          src={author?.imageUrl}
          alt={`${author.username}'s profile picture`}
          className="h-14 w-14 rounded-full"
          height={56}
          width={56}
           />
        <div className="flex flex-col">
          <div className="flex font-bold text-slate-300 gap-1">
            <span>{`@${author?.username}`}</span> <span className="font-thin">{`· ${dayjs(post.createdAt).fromNow()}`}</span>
          </div>
          <span>{post.content}</span>
        </div>
      </div>
    )
  }
  const CreatePostWizard = () => {
    const { user } = useUser();

    if (!user) return null;

    return (
      <div className="flex w-full gap-3">
        <Image
          src={user?.imageUrl}
          alt={`${user.username}'s profile picture`}
          className="h-14 w-14 rounded-full"
          height={56}
          width={56}
           />
        <input
          placeholder="Type some emojis!"
          className="grow bg-transparent outline-none" />
      </div>
    )
  }



  if (isLoading) return <div>Loading...</div>

  if (!data) return <div>Something went wrong</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen w-full">
        <div className="w-full border-x h-full md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && <SignInButton />}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {
              [...data, ...data]?.map((fullPost) => (
                <PostView {...fullPost} key={fullPost.post.id} />
              ))
            }
          </div>
        </div>
      </main>
    </>
  );
}
